[2024-09-16T11:38:29.413+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-16T11:38:29.448+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_alchemy.say_welcome_alchemy manual__2024-09-16T11:38:27.549142+00:00 [queued]>
[2024-09-16T11:38:29.472+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_alchemy.say_welcome_alchemy manual__2024-09-16T11:38:27.549142+00:00 [queued]>
[2024-09-16T11:38:29.474+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-16T11:38:29.511+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): say_welcome_alchemy> on 2024-09-16 11:38:27.549142+00:00
[2024-09-16T11:38:29.525+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1694) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-16T11:38:29.529+0000] {standard_task_runner.py:72} INFO - Started process 1696 to run task
[2024-09-16T11:38:29.529+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_alchemy', 'say_welcome_alchemy', 'manual__2024-09-16T11:38:27.549142+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/test_alchemy_dags.py', '--cfg-path', '/tmp/tmp8n8tqztg']
[2024-09-16T11:38:29.531+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask say_welcome_alchemy
[2024-09-16T11:38:29.624+0000] {task_command.py:467} INFO - Running <TaskInstance: test_alchemy.say_welcome_alchemy manual__2024-09-16T11:38:27.549142+00:00 [running]> on host 9978fde86398
[2024-09-16T11:38:29.806+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='test_alchemy' AIRFLOW_CTX_TASK_ID='say_welcome_alchemy' AIRFLOW_CTX_EXECUTION_DATE='2024-09-16T11:38:27.549142+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-16T11:38:27.549142+00:00'
[2024-09-16T11:38:29.808+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-16T11:38:29.839+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-16T11:38:29.841+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Hallo !"']
[2024-09-16T11:38:29.865+0000] {subprocess.py:86} INFO - Output:
[2024-09-16T11:38:29.872+0000] {subprocess.py:93} INFO - Hallo !
[2024-09-16T11:38:29.874+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-16T11:38:29.950+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-16T11:38:29.952+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_alchemy, task_id=say_welcome_alchemy, run_id=manual__2024-09-16T11:38:27.549142+00:00, execution_date=20240916T113827, start_date=20240916T113829, end_date=20240916T113829
[2024-09-16T11:38:30.030+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-16T11:38:30.084+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-16T11:38:30.096+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
