[2024-09-16T16:05:45.099+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-16T16:05:45.114+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_load_database.say_welcome manual__2024-09-16T16:05:43.511808+00:00 [queued]>
[2024-09-16T16:05:45.122+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_load_database.say_welcome manual__2024-09-16T16:05:43.511808+00:00 [queued]>
[2024-09-16T16:05:45.122+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-16T16:05:45.134+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): say_welcome> on 2024-09-16 16:05:43.511808+00:00
[2024-09-16T16:05:45.141+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1528) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-16T16:05:45.142+0000] {standard_task_runner.py:72} INFO - Started process 1530 to run task
[2024-09-16T16:05:45.142+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_load_database', 'say_welcome', 'manual__2024-09-16T16:05:43.511808+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/test_load_db_dags.py', '--cfg-path', '/tmp/tmp_4yia244']
[2024-09-16T16:05:45.144+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask say_welcome
[2024-09-16T16:05:45.182+0000] {task_command.py:467} INFO - Running <TaskInstance: test_load_database.say_welcome manual__2024-09-16T16:05:43.511808+00:00 [running]> on host e54c4d73c780
[2024-09-16T16:05:45.396+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='test_load_database' AIRFLOW_CTX_TASK_ID='say_welcome' AIRFLOW_CTX_EXECUTION_DATE='2024-09-16T16:05:43.511808+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-16T16:05:43.511808+00:00'
[2024-09-16T16:05:45.397+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-16T16:05:45.408+0000] {logging_mixin.py:190} INFO - Welcome to Apache Airflow
[2024-09-16T16:05:45.409+0000] {logging_mixin.py:190} INFO - First run this task then execute task transform_csv and transform_json parallel
[2024-09-16T16:05:45.409+0000] {logging_mixin.py:190} INFO - Then finally run task end_task
[2024-09-16T16:05:45.409+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-16T16:05:45.418+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-16T16:05:45.418+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_load_database, task_id=say_welcome, run_id=manual__2024-09-16T16:05:43.511808+00:00, execution_date=20240916T160543, start_date=20240916T160545, end_date=20240916T160545
[2024-09-16T16:05:45.477+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-16T16:05:45.501+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-16T16:05:45.503+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
