[2024-09-17T00:50:15.418+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-17T00:50:15.453+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_load_database.say_welcome manual__2024-09-17T00:50:13.498204+00:00 [queued]>
[2024-09-17T00:50:15.469+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_load_database.say_welcome manual__2024-09-17T00:50:13.498204+00:00 [queued]>
[2024-09-17T00:50:15.470+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-17T00:50:15.498+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): say_welcome> on 2024-09-17 00:50:13.498204+00:00
[2024-09-17T00:50:15.512+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=101) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-17T00:50:15.515+0000] {standard_task_runner.py:72} INFO - Started process 103 to run task
[2024-09-17T00:50:15.514+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_load_database', 'say_welcome', 'manual__2024-09-17T00:50:13.498204+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/test_load_db_dags.py', '--cfg-path', '/tmp/tmpr1sodc3e']
[2024-09-17T00:50:15.518+0000] {standard_task_runner.py:105} INFO - Job 62: Subtask say_welcome
[2024-09-17T00:50:15.602+0000] {task_command.py:467} INFO - Running <TaskInstance: test_load_database.say_welcome manual__2024-09-17T00:50:13.498204+00:00 [running]> on host e54c4d73c780
[2024-09-17T00:50:16.031+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='test_load_database' AIRFLOW_CTX_TASK_ID='say_welcome' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T00:50:13.498204+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-17T00:50:13.498204+00:00'
[2024-09-17T00:50:16.033+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-17T00:50:16.057+0000] {logging_mixin.py:190} INFO - Welcome to Apache Airflow
[2024-09-17T00:50:16.058+0000] {logging_mixin.py:190} INFO - First run this task then execute task transform_csv and transform_json parallel
[2024-09-17T00:50:16.059+0000] {logging_mixin.py:190} INFO - Then finally run task end_task
[2024-09-17T00:50:16.060+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-17T00:50:16.078+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-17T00:50:16.080+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_load_database, task_id=say_welcome, run_id=manual__2024-09-17T00:50:13.498204+00:00, execution_date=20240917T005013, start_date=20240917T005015, end_date=20240917T005016
[2024-09-17T00:50:16.137+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-17T00:50:16.185+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-17T00:50:16.190+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
