[2024-09-16T11:38:37.944+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-16T11:38:37.980+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_alchemy.say_end_alchemy manual__2024-09-16T11:38:27.549142+00:00 [queued]>
[2024-09-16T11:38:38.007+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_alchemy.say_end_alchemy manual__2024-09-16T11:38:27.549142+00:00 [queued]>
[2024-09-16T11:38:38.009+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-16T11:38:38.048+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): say_end_alchemy> on 2024-09-16 11:38:27.549142+00:00
[2024-09-16T11:38:38.059+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1743) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-16T11:38:38.062+0000] {standard_task_runner.py:72} INFO - Started process 1745 to run task
[2024-09-16T11:38:38.063+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_alchemy', 'say_end_alchemy', 'manual__2024-09-16T11:38:27.549142+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/test_alchemy_dags.py', '--cfg-path', '/tmp/tmp0b6dcktb']
[2024-09-16T11:38:38.068+0000] {standard_task_runner.py:105} INFO - Job 30: Subtask say_end_alchemy
[2024-09-16T11:38:38.177+0000] {task_command.py:467} INFO - Running <TaskInstance: test_alchemy.say_end_alchemy manual__2024-09-16T11:38:27.549142+00:00 [running]> on host 9978fde86398
[2024-09-16T11:38:38.363+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='test_alchemy' AIRFLOW_CTX_TASK_ID='say_end_alchemy' AIRFLOW_CTX_EXECUTION_DATE='2024-09-16T11:38:27.549142+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-16T11:38:27.549142+00:00'
[2024-09-16T11:38:38.365+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-16T11:38:38.409+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-16T11:38:38.411+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Good Bye ..."']
[2024-09-16T11:38:38.438+0000] {subprocess.py:86} INFO - Output:
[2024-09-16T11:38:38.442+0000] {subprocess.py:93} INFO - Good Bye ...
[2024-09-16T11:38:38.443+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-16T11:38:38.503+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-16T11:38:38.505+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_alchemy, task_id=say_end_alchemy, run_id=manual__2024-09-16T11:38:27.549142+00:00, execution_date=20240916T113827, start_date=20240916T113837, end_date=20240916T113838
[2024-09-16T11:38:38.563+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-16T11:38:38.607+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-16T11:38:38.621+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
