[2024-09-14T16:12:02.620+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-14T16:12:02.667+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_pgadmin.create_table_customer_bash manual__2024-09-14T16:11:58.039528+00:00 [queued]>
[2024-09-14T16:12:02.693+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_pgadmin.create_table_customer_bash manual__2024-09-14T16:11:58.039528+00:00 [queued]>
[2024-09-14T16:12:02.694+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-14T16:12:02.728+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): create_table_customer_bash> on 2024-09-14 16:11:58.039528+00:00
[2024-09-14T16:12:02.740+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=418) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-14T16:12:02.743+0000] {standard_task_runner.py:72} INFO - Started process 419 to run task
[2024-09-14T16:12:02.743+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_pgadmin', 'create_table_customer_bash', 'manual__2024-09-14T16:11:58.039528+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/test_pgadmin_dags.py', '--cfg-path', '/tmp/tmp_mv9p_46']
[2024-09-14T16:12:02.746+0000] {standard_task_runner.py:105} INFO - Job 131: Subtask create_table_customer_bash
[2024-09-14T16:12:02.836+0000] {task_command.py:467} INFO - Running <TaskInstance: test_pgadmin.create_table_customer_bash manual__2024-09-14T16:11:58.039528+00:00 [running]> on host 0a5b2fe35fbd
[2024-09-14T16:12:02.992+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='test_pgadmin' AIRFLOW_CTX_TASK_ID='create_table_customer_bash' AIRFLOW_CTX_EXECUTION_DATE='2024-09-14T16:11:58.039528+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-14T16:11:58.039528+00:00'
[2024-09-14T16:12:02.993+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-14T16:12:03.023+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-14T16:12:03.025+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        psql postgresql://***:***@172.19.0.4:5432/***_retail -c "\n        CREATE TABLE IF NOT EXISTS customer (\n            customer_id SERIAL PRIMARY KEY,\n            customer_name VARCHAR(255),\n            email_address VARCHAR(255)\n        );\n        "\n        ']
[2024-09-14T16:12:03.043+0000] {subprocess.py:86} INFO - Output:
[2024-09-14T16:12:03.246+0000] {subprocess.py:93} INFO - CREATE TABLE
[2024-09-14T16:12:03.249+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-14T16:12:03.303+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-14T16:12:03.305+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_pgadmin, task_id=create_table_customer_bash, run_id=manual__2024-09-14T16:11:58.039528+00:00, execution_date=20240914T161158, start_date=20240914T161202, end_date=20240914T161203
[2024-09-14T16:12:03.405+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-14T16:12:03.458+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-14T16:12:03.467+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
