[2024-09-13T09:11:02.879+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T09:11:02.911+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_product_bash.retailDataWithAirflow manual__2024-09-13T09:10:58.820660+00:00 [queued]>
[2024-09-13T09:11:02.927+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_product_bash.retailDataWithAirflow manual__2024-09-13T09:10:58.820660+00:00 [queued]>
[2024-09-13T09:11:02.928+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-13T09:11:02.953+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): retailDataWithAirflow> on 2024-09-13 09:10:58.820660+00:00
[2024-09-13T09:11:02.964+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3472) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-13T09:11:02.967+0000] {standard_task_runner.py:72} INFO - Started process 3473 to run task
[2024-09-13T09:11:02.968+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_product_bash', 'retailDataWithAirflow', 'manual__2024-09-13T09:10:58.820660+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/retailData_dags.py', '--cfg-path', '/tmp/tmpbehs6fsg']
[2024-09-13T09:11:02.969+0000] {standard_task_runner.py:105} INFO - Job 84: Subtask retailDataWithAirflow
[2024-09-13T09:11:03.055+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_product_bash.retailDataWithAirflow manual__2024-09-13T09:10:58.820660+00:00 [running]> on host 9c5d837b6f3b
[2024-09-13T09:11:03.234+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='customer_product_bash' AIRFLOW_CTX_TASK_ID='retailDataWithAirflow' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T09:10:58.820660+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-13T09:10:58.820660+00:00'
[2024-09-13T09:11:03.236+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T09:11:03.272+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-13T09:11:03.274+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/script/retailDataWithAirflow.py']
[2024-09-13T09:11:03.294+0000] {subprocess.py:86} INFO - Output:
[2024-09-13T09:11:06.215+0000] {subprocess.py:93} INFO - /opt/***/dags/script/retailDataWithAirflow.py:115: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-09-13T09:11:06.217+0000] {subprocess.py:93} INFO -   df.to_sql(name=self.table_name, con=self.engine, index=False, if_exists='replace')
[2024-09-13T09:11:06.608+0000] {subprocess.py:93} INFO - /opt/***/dags/script/retailDataWithAirflow.py:115: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-09-13T09:11:06.609+0000] {subprocess.py:93} INFO -   df.to_sql(name=self.table_name, con=self.engine, index=False, if_exists='replace')
[2024-09-13T09:11:06.610+0000] {subprocess.py:93} INFO - Error loading data to database: 'Engine' object has no attribute 'cursor'
[2024-09-13T09:11:06.611+0000] {subprocess.py:93} INFO - Error loading data to database: 'Engine' object has no attribute 'cursor'
[2024-09-13T09:11:06.802+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-13T09:11:06.861+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T09:11:06.863+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_product_bash, task_id=retailDataWithAirflow, run_id=manual__2024-09-13T09:10:58.820660+00:00, execution_date=20240913T091058, start_date=20240913T091102, end_date=20240913T091106
[2024-09-13T09:11:06.928+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-13T09:11:06.974+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-13T09:11:06.977+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
