[2024-09-16T14:47:50.908+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-16T14:47:50.941+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_alchemy.say_welcome_alchemy manual__2024-09-16T14:47:49.064669+00:00 [queued]>
[2024-09-16T14:47:50.960+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_alchemy.say_welcome_alchemy manual__2024-09-16T14:47:49.064669+00:00 [queued]>
[2024-09-16T14:47:50.962+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-16T14:47:50.990+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): say_welcome_alchemy> on 2024-09-16 14:47:49.064669+00:00
[2024-09-16T14:47:51.002+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=416) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-16T14:47:51.005+0000] {standard_task_runner.py:72} INFO - Started process 417 to run task
[2024-09-16T14:47:51.005+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_alchemy', 'say_welcome_alchemy', 'manual__2024-09-16T14:47:49.064669+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/test_alchemy_dags.py', '--cfg-path', '/tmp/tmpihhxa5i8']
[2024-09-16T14:47:51.008+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask say_welcome_alchemy
[2024-09-16T14:47:51.102+0000] {task_command.py:467} INFO - Running <TaskInstance: test_alchemy.say_welcome_alchemy manual__2024-09-16T14:47:49.064669+00:00 [running]> on host e54c4d73c780
[2024-09-16T14:47:51.288+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='test_alchemy' AIRFLOW_CTX_TASK_ID='say_welcome_alchemy' AIRFLOW_CTX_EXECUTION_DATE='2024-09-16T14:47:49.064669+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-16T14:47:49.064669+00:00'
[2024-09-16T14:47:51.291+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-16T14:47:51.323+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-16T14:47:51.325+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Hallo !"']
[2024-09-16T14:47:51.345+0000] {subprocess.py:86} INFO - Output:
[2024-09-16T14:47:51.348+0000] {subprocess.py:93} INFO - Hallo !
[2024-09-16T14:47:51.350+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-16T14:47:51.399+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-16T14:47:51.400+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_alchemy, task_id=say_welcome_alchemy, run_id=manual__2024-09-16T14:47:49.064669+00:00, execution_date=20240916T144749, start_date=20240916T144750, end_date=20240916T144751
[2024-09-16T14:47:51.465+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-16T14:47:51.528+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-16T14:47:51.538+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
