[2024-09-16T14:48:27.482+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-16T14:48:27.516+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_alchemy.say_welcome_alchemy manual__2024-09-16T14:48:25.880015+00:00 [queued]>
[2024-09-16T14:48:27.536+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_alchemy.say_welcome_alchemy manual__2024-09-16T14:48:25.880015+00:00 [queued]>
[2024-09-16T14:48:27.537+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-16T14:48:27.568+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): say_welcome_alchemy> on 2024-09-16 14:48:25.880015+00:00
[2024-09-16T14:48:27.579+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=451) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-16T14:48:27.582+0000] {standard_task_runner.py:72} INFO - Started process 452 to run task
[2024-09-16T14:48:27.583+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_alchemy', 'say_welcome_alchemy', 'manual__2024-09-16T14:48:25.880015+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/test_alchemy_dags.py', '--cfg-path', '/tmp/tmpmr38owm4']
[2024-09-16T14:48:27.585+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask say_welcome_alchemy
[2024-09-16T14:48:27.669+0000] {task_command.py:467} INFO - Running <TaskInstance: test_alchemy.say_welcome_alchemy manual__2024-09-16T14:48:25.880015+00:00 [running]> on host e54c4d73c780
[2024-09-16T14:48:27.888+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='test_alchemy' AIRFLOW_CTX_TASK_ID='say_welcome_alchemy' AIRFLOW_CTX_EXECUTION_DATE='2024-09-16T14:48:25.880015+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-16T14:48:25.880015+00:00'
[2024-09-16T14:48:27.889+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-16T14:48:27.926+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-16T14:48:27.928+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Hallo !"']
[2024-09-16T14:48:27.951+0000] {subprocess.py:86} INFO - Output:
[2024-09-16T14:48:27.954+0000] {subprocess.py:93} INFO - Hallo !
[2024-09-16T14:48:27.955+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-16T14:48:28.007+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-16T14:48:28.009+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_alchemy, task_id=say_welcome_alchemy, run_id=manual__2024-09-16T14:48:25.880015+00:00, execution_date=20240916T144825, start_date=20240916T144827, end_date=20240916T144828
[2024-09-16T14:48:28.082+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-16T14:48:28.139+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-16T14:48:28.148+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
